### ISSUE TITLE
Spot check files to make sure all look OK

### ISSUE THREAD

**Issue by karindalziel** [CDRH/lewisandclark#10]
Spot check files (maybe every 10th to 20th file, depending on similarity, and pay special attention to files with out of the ordinary filenames) to make sure that nothing in the scripts I wrote messed anything up. 
### 1: The XML: ID on the files should match the filenames: (TEI is the root element)

`<TEI xmlns="http://www.tei-c.org/ns/1.0" xml:id="lc.jrn.1805-08-23">`
### 2: Category/SubCategory/Topics

I have added a section that looks like this to the header of each TEI file: 

``` xml
<textClass>
            <keywords scheme="original" n="category">
               <term>Journals</term>
            </keywords>
            <keywords scheme="original" n="subcategory">
               <term>Journal Entries</term>
            </keywords>
            <keywords scheme="original" n="topic">
               <term/>
            </keywords>
            <keywords scheme="lcsh" n="keywords">
               <term/>
            </keywords>
         </textClass>
```

Check that the category and sub category look correct, and that nothing seems malformed. 
### 1: Bibls in TEI header

Things I changed: 
- Split up the bibls (it used to be one long bibl, I split them after the biblScope. 
- Reassigned author of bibls based on the book title. Before all of them had Lewis and Clark as authors. 
- Added an xml:id to the authors. 

things to look for:
- bibls that don't look split up correctly
- bibls with incorrect authors
- authors with incorrect xml:id's
### 2: Added Geo to headers

The geo added to headers should look like: 

``` xml
<geoDecl datum="WGS" xml:id="lc.geo.1806-05-08.01">
            <placeName/>
            <geo>46.4667 -115.7833</geo>
            <note>Camped in Clearwater County, ID, a few miles out from Orofino.</note>
         </geoDecl>
```

Please keep a list of any files missing geo encoding that needs it. If a file does not have a geographic place associated with it and no geoDecl in the header, we may need to remove the @n attribute from the `<div type='entry'>`

``` xml
<div type="entry" xml:id="lc.jrn.1806-04-07.01" n="">
```
### 3: Entries have xml:id's

``` xml
<div type="entry" xml:id="lc.jrn.1806-04-07.01">
```

All entries should have an XML ID that is the filename with .01, .02 etc after it (should be numbered down the page)

**Comment by sduke** [comment]
Spot Checks:
lc.jrn.1805-11-13
lc.jrn.1805-11-14
lc.jrn.1805-11-15
lc.jrn.1805-11-16
lc.jrn.1805-11-17
lc.jrn.1805-11-18
lc.jrn.1805-11-19
lc.jrn.1805-11-20
lc.jrn.1805-11-21
lc.jrn.1805-11-22
lc.jrn.1805-11-23
lc.jrn.1805-11-24
lc.jrn.1805-11-27
lc.jrn.1805-11-28

**Comment by sduke** [comment]
BIG CHANGE:
lc.jrn.1805-11-29: created new <geoDecl> location. Lewis camped at a different point than the rest of the group.
The following points also received this new <geoDecl> tag:
lc.jrn.1805-11-30
lc.jrn.1805-12-01
lc.jrn.1805-12-02
lc.jrn.1805-12-03
lc.jrn.1805-12-04
lc.jrn.1805-12-05
lc.jrn.1805-12-06

**Comment by sduke** [comment]
Spot Checks:
lc.jrn.1805-12-02
lc.jrn.1805-12-03
lc.jrn.1805-12-04
lc.jrn.1805-12-05
lc.jrn.1805-12-06
lc.jrn.1805-12-08
lc.jrn.1805-12-09
lc.jrn.1805-12-10
lc.jrn.1805-12-11
lc.jrn.1805-12-12
lc.jrn.1805-12-13
lc.jrn.1805-12-14
lc.jrn.1805-12-15
lc.jrn.1805-12-16
lc.jrn.1805-12-17
lc.jrn.1805-12-18
lc.jrn.1805-12-19
lc.jrn.1805-12-20
lc.jrn.1805-12-21
lc.jrn.1805-12-22-24
lc.jrn.1805-12-22
lc.jrn.1805-12-23
lc.jrn.1805-12-24
lc.jrn.1805-12-25
lc.jrn.1805-12-26
lc.jrn.1805-12-27
lc.jrn.1805-12-28
lc.jrn.1805-12-29
lc.jrn.1805-12-30
lc.jrn.1805-12-31-1
lc.jrn.1805-12-31
lc.jrn.1805-1806.winter.introduction
lc.jrn.1805-1806.winter.part1
lc.jrn.1805-1806.winter.part2
lc.jrn.1805-1806.winter.part3
lc.jrn.1806-01-01
lc.jrn.1806-01-02
lc.jrn.1806-01-03
lc.jrn.1806-01-04
lc.jrn.1806-01-05
lc.jrn.1806-01-09
lc.jrn.1806-01-10
lc.jrn.1806-01-11
lc.jrn.1806-01-12
lc.jrn.1806-01-13
lc.jrn.1806-01-14
lc.jrn.1806-01-15-16
lc.jrn.1806-01-15
lc.jrn.1806-01-16
lc.jrn.1806-01-17
lc.jrn.1806-01-18
lc.jrn.1806-01-19
lc.jrn.1806-01-20
lc.jrn.1806-01-21
lc.jrn.1806-01-22
lc.jrn.1806-01-23
lc.jrn.1806-01-24
lc.jrn.1806-01-25
lc.jrn.1806-01-26
lc.jrn.1806-01-27
lc.jrn.1806-01-28
lc.jrn.1806-01-29
lc.jrn.1806-01-30
lc.jrn.1806-01-31-1
lc.jrn.1806-01-31

**Comment by sduke** [comment]
Spot Checks:
lc.jrn.1806-02-01
lc.jrn.1806-02-02
lc.jrn.1806-02-03
lc.jrn.1806-02-04
lc.jrn.1806-02-05
lc.jrn.1806-02-06
lc.jrn.1806-02-07
lc.jrn.1806-02-08
lc.jrn.1806-02-09
lc.jrn.1806-02-10
lc.jrn.1806-02-11
lc.jrn.1806-02-12
lc.jrn.1806-02-13
lc.jrn.1806-02-14
lc.jrn.1806-02-15
lc.jrn.1806-02-16
lc.jrn.1806-02-17
lc.jrn.1806-02-18
lc.jrn.1806-02-19
lc.jrn.1806-02-20
lc.jrn.1806-02-21
lc.jrn.1806-02-22
lc.jrn.1806-02-23
lc.jrn.1806-02-24
lc.jrn.1806-02-25
lc.jrn.1806-02-26
lc.jrn.1806-02-27
lc.jrn.1806-02-28-1
lc.jrn.1806-02-28
lc.jrn.1806-03-01
lc.jrn.1806-03-02
lc.jrn.1806-03-03
lc.jrn.1806-03-04
lc.jrn.1806-03-05
lc.jrn.1806-03-06
lc.jrn.1806-03-07
lc.jrn.1806-03-08
lc.jrn.1806-03-09
lc.jrn.1806-03-10
lc.jrn.1806-03-11
lc.jrn.1806-03-12
lc.jrn.1806-03-13
lc.jrn.1806-03-14
lc.jrn.1806-03-15
lc.jrn.1806-03-16
lc.jrn.1806-03-17
lc.jrn.1806-03-18
lc.jrn.1806-03-19
lc.jrn.1806-03-20
lc.jrn.1806-03-21
lc.jrn.1806-03-22
lc.jrn.1806-03-31-1

**Comment by sduke** [comment]
Spot Checks:
lc.jrn.1806-04-01
lc.jrn.1806-04-05
lc.jrn.1806-04-06
lc.jrn.1806-04-07
lc.jrn.1806-04-08
lc.jrn.1806-04-10
lc.jrn.1806-04-11
lc.jrn.1806-04-16
lc.jrn.1806-04-17
lc.jrn.1806-04-19
lc.jrn.1806-04-20
lc.jrn.1806-04-27
lc.jrn.1806-04-28
lc.jrn.1806-04-30-1
lc.jrn.1806-05-10
lc.jrn.1806-05-11
lc.jrn.1806-05-12
lc.jrn.1806-05-14
lc.jrn.1806-05-15
lc.jrn.1806-05-16
lc.jrn.1806-05-17
lc.jrn.1806-05-18
lc.jrn.1806-05-19
lc.jrn.1806-05-20
lc.jrn.1806-05-21
lc.jrn.1806-05-22
lc.jrn.1806-05-23
lc.jrn.1806-05-24
lc.jrn.1806-05-25
lc.jrn.1806-05-26
lc.jrn.1806-05-28
lc.jrn.1806-05-29
lc.jrn.1806-05-30
lc.jrn.1806-05-31-1
lc.jrn.1806-05-31
lc.jrn.1806-06-01
lc.jrn.1806-06-02
lc.jrn.1806-06-03
lc.jrn.1806-06-04
lc.jrn.1806-06-05
lc.jrn.1806-06-06
lc.jrn.1806-06-07
lc.jrn.1806-06-08
lc.jrn.1806-06-09
lc.jrn.1806-06-10
lc.jrn.1806-06-11
lc.jrn.1806-06-12
lc.jrn.1806-06-13
lc.jrn.1806-06-14
lc.jrn.1806-06-18
lc.jrn.1806-06-19
lc.jrn.1806-06-20
lc.jrn.1806-06-21
lc.jrn.1806-06-22
lc.jrn.1806-06-23
lc.jrn.1806-06-24
lc.jrn.1806-06-30-1
lc.jrn.1806-06-30
lc.jrn.1806-07-01
lc.jrn.1806-07-02
lc.jrn.1806-07-04
lc.jrn.1806-07-08
lc.jrn.1806-07-09
lc.jrn.1806-07-10
lc.jrn.1806-07-11
lc.jrn.1806-07-12
lc.jrn.1806-07-13
lc.jrn.1806-07-14
lc.jrn.1806-07-15

BIG CHANGE: Added additional geo point, as the party camp was not included
lc.jrn.1806-07-16
lc.jrn.1806-07-17
lc.jrn.1806-07-18
lc.jrn.1806-07-19
lc.jrn.1806-07-20
lc.jrn.1806-07-21
lc.jrn.1806-07-22
lc.jrn.1806-07-23
lc.jrn.1806-07-24
lc.jrn.1806-07-25
lc.jrn.1806-07-26
lc.jrn.1806-07-27
lc.jrn.1806-07-28
lc.jrn.1806-07-29

Spot Checks:
lc.jrn.1806-07-30
lc.jrn.1806-07-31-1
lc.jrn.1806-07-31
lc.jrn.1806-08-01
lc.jrn.1806-08-02
lc.jrn.1806-08-03
lc.jrn.1806-08-04
lc.jrn.1806-08-05
lc.jrn.1806-08-06
lc.jrn.1806-08-07
lc.jrn.1806-08-08
lc.jrn.1806-08-09
lc.jrn.1806-08-10
lc.jrn.1806-08-11
lc.jrn.1806-08-14
lc.jrn.1806-08-15
lc.jrn.1806-08-16
lc.jrn.1806-08-26
lc.jrn.1806-08-31-1
lc.jrn.1806-09-09
lc.jrn.1806-09-19
lc.jrn.1806-09-23
lc.jrn.1806-09-24
lc.jrn.1806-09-25
lc.jrn.1806-09-26
lc.jrn.1806-09-30-1
lc.jrn.1806.postexpedition.introduction
lc.jrn.1806.postexpedition.part1
lc.jrn.1806.postexpedition.part2

End of XML edits. DONE.

**Comment by jduss4** [comment]
Holy cow that is a lot of spotchecking. Since this site has been public for a while now, I'm going to assume that we are done with this issue!!!
