### ISSUE TITLE
Image URLs / Storage

### ISSUE THREAD

**Issue by techgique** [CDRH/lewisandclark#102]
Image URLs are hardcoded with live site's FQDN.
Karin has images stored in data_images on Rosie

Do we want to move them to cors1601 and remove FQDN from links?

**Comment by karindalziel** [comment]
OK another part to this issue, we need to decide where to link to the xml for the site. 

A couple of other site examples: 
- OSCYS: http://earlywashingtondc.org/files/oscys/tei/oscys.case.0081.003.xml
- Austen: http://austen.unl.edu/aus.001.xml (these files are just in the static folder, I believe)

**Comment by karindalziel** [comment]
thinking this through, once we have the API, the XML will always be stored in one central location so it is accessible from the API. so really, it shouldn't come from the root URL

**Comment by karindalziel** [comment]
Collecting ideas for a data repo URL: 

* cdrhmedia.unl.edu
* cdrhstuff
* cdrhrummagedrawer
* cdrhatheneum
* cdrhdata.unl.edu
* cdrharchive

**Comment by techgique** [comment]
cdrhmedia.unl.edu CNAME in place.
Request for TLS cert in, but not processed yet.
Browse site and make sure images are serving properly through HTTPS and no mixed-content problems after set up.

**Comment by karindalziel** [comment]
DOOOONEEEEE
