### ISSUE TITLE
FAVICON

### ISSUE THREAD

**Issue by karindalziel** [CDRH/lewisandclark#183]

**Comment by karindalziel** [comment]
* http://stackoverflow.com/questions/30824294/mobile-favicons
* http://stackoverflow.com/questions/25430085/how-to-use-multiple-favicon-ico-sizes-with-favicon-link-tag-helper-in-rails-4

**Comment by karindalziel** [comment]
https://github.com/CDRH/lewisandclark/pull/185/files

**Comment by techgique** [comment]
The answer to your first SO link seems best: http://stackoverflow.com/a/30839701

Things I noticed:
Don't use "shortcut" anymore. `<link rel="icon" href="/favicon.ico">`
Use multiple sizes in .ico file. 16, 32, and 48.
Add `<meta name="Journals of the Lewis and Clark Expedition">` for a friendlier link name if someone creates a link on their mobile home screen.

**Comment by techgique** [comment]
Closed with #188
