### ISSUE TITLE
Possibly incorrect name entities

### ISSUE THREAD

**Issue by karindalziel** [CDRH/lewisandclark#196]
https://cdrhtest2.unl.edu/item/lc.jrn.1804-04-30-1#lc.jrn.1804-04-30-1.01

![screen shot 2016-12-12 at 11 41 38 am](https://cloud.githubusercontent.com/assets/284315/21109773/256d05fa-c060-11e6-93cf-c64c92684e43.png)
![screen shot 2016-12-12 at 11 41 30 am](https://cloud.githubusercontent.com/assets/284315/21109775/26ad1b6c-c060-11e6-8c6e-4496ae5af4c1.png)

**Comment by jduss4** [comment]
Laura thinks that there are likely two separate individuals and this is okay to leave
