### ISSUE TITLE
Link forwards to improve

### ISSUE THREAD

**Issue by karindalziel** [CDRH/lewisandclark#200]
If you look through the links at site:lewisandclarkjournals.unl.edu almost none of them are forwarding as elected. You get a 404 page instead. 

Related, links like this: 

* https://lewisandclarkjournals.unl.edu/search.php
* https://lewisandclarkjournals.unl.edu/search.php?keyword=rattlesnake

Are going to a blank page

**Comment by techgique** [comment]
These were wrapped up last Tuesday
