### ISSUE TITLE
Bad old, old URL's

### ISSUE THREAD

**Issue by karindalziel** [CDRH/lewisandclark#215]
Jason and Laura helped uncover yet another place where Lewis and Clark URL's are bad.

Some time ago (when Lewis and Clark was still running on tamino, I assume) the site was ingested into the library catalog. These links are broken.

http://encore.unl.edu/iii/encore/record/C__Rx1509743__SLewis%20and%20Clark%20journals%20%20November%2011%2C%201803__Orightresult__U__X2?lang=eng&suite=cobalt

if you click on "repository source" you'll se the link goes to a 404 page

the link format looks like this: http://lewisandclarkjournals.unl.edu/content/1803-11-11.html

I'm hoping this will be an easy enough rule to add to the URL forwarding

**Comment by techgique** [comment]
Wanted to double-check there weren't other types of links besides those to journal entries.

I believe this search retrieves all the documents in that collection: http://encore.unl.edu/iii/encore/search/C__St%3A%28*%29%20c%3Arepo_UNL_LC__O-date__U__X0?lang=eng&suite=cobalt

Sorting those results by date seems to show both the beginning and end of that result list are only journal entries, so will only focus on redirecting the style of link noted above.

**Comment by techgique** [comment]
Karin compared the collection count (1025) with the journal file count (1136) and said it sounds about right with introduction files etc which aren't in the Encore collection.
